name: tiny_3d_renderer
description: A tiny 3d renderer which shows the basics of the 3d to 2d camera projection.
# version: 1.0.0
#homepage: https://www.example.com
#author: GDur <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  vector_math: any
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
